import Nav from "@/components/Nav/Nav"
import "./globals.css"

export const metadata = {
  title: "Fearless coder",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
