import Nav from '@/components/Nav/Nav'
import './globals.css'
import { ContextProvider } from '@/context/userContex'

export const metadata = {
  title: 'Fearless coder',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body>
        <ContextProvider>
          <Nav />
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
